### ISSUE TITLE
Energy ID does not show any entity

### ISSUE THREAD

**Issue by tenten95905** [tijsverkoyen/HomeAssistant-EnergyID#11]
Hi,

I have tried to add your repository to HACS. Unfortunately, I'm not able to see any device or entities.
Why? Does it still work?

Best regards

![image](https://github.com/tijsverkoyen/HomeAssistant-EnergyID/assets/142319682/1b2ceef1-e966-4d98-8c48-fbaedaba5a57)

**Comment by tijsverkoyen** [comment]
My first guess would be that your credentials do not have the correct rights. There should be at least a plant.

Are you using kiosk mode or open api credentials?

**Comment by tijsverkoyen** [comment]
I still use it and it works to my knowledge.
I will check in the next week

**Comment by tenten95905** [comment]
Thanks, it worked the day after magically.
