### ISSUE TITLE
Implement analyses/peakPower, analyses/capacity, and analyses/powerPeaks

### ISSUE THREAD

**Issue by liviooo** [tijsverkoyen/HomeAssistant-EnergyID#12]
Hi Tijs,

Any planned updates for EnergyID now that they have Premium plans activated?

I'm a member of a premium group in EnergyID and a lot of new features have been released.

Thnx

**Comment by tijsverkoyen** [comment]
Hi, to be honest: I was not aware of the premium plans.
Which features would you expect to be available in this integration?

**Comment by liviooo** [comment]
Things like this would be nice:

/records/{id}/analyses/peakPower
/records/{id}/analyses/capacity
/records/{id}/analyses/powerPeaks

All possibilities listed on https://api.energyid.eu/api-reference/index.html

**Comment by tijsverkoyen** [comment]
As a service?
From what I can see there is a lot of data returned, so translating this to multiple entities will need further research.
Do you want to contribute code?

**Comment by liviooo** [comment]
/records/{id}/analyses/peakPower should only return 1 number per search, and it is only valid for electricity meters, so that won't be that hard I guess :-)

**Comment by tijsverkoyen** [comment]
@liviooo would you be willing to share a token with me so I can see the data of the response? 
Because I don't have a premium subscription, nor a digital meter ;-)

You can mail it to me at `energy-ha [at] verkoyen [dot] eu`

**Comment by tijsverkoyen** [comment]
@liviooo your feedback would be welcome. Below is just a draft, so it could change.

# Change config flow
When configuring the integration it is asked if a premium subscription is active. If so the analyses entities are created and updated.

## Todo
* Check how this should be handled for existing users.
* Can the setting be changed if an error for the analyse endpoints is received?

# analyses/peakPower

I would create the following entities, and update them once a day

* Current Month PeakPower Power (kW)
* Current Month PeakPower Time (datetime)
* Last Month PeakPower Power (kw)
* Last Month PeakPower Time (datetime)

The data can be retrieved in 1 call. So only 1 coordinator for these entities is needed.

````
curl --location 'https://api.energyid.eu//api/v1/records/[recordId]/analyses/peakPower?start=[start of 1 month ago]&end=[last day of current month]' \
--header 'Authorization: apikey XXXX'
````

# analyses/capacity
I don't have a working example at the moment, but purely based on the documentation I think the following entities would be beneficial:

* Current Month Capacity Total (Wh)
* Current Month Capacity Min (Wh)
* Current Month Capacity Max (Wh)
* Current Month Capacity Mean (Wh)

The data can be retrieved in 1 call. So only 1 coordinator for these entities is needed.

````
curl --location 'https://api.energyid.eu//api/v1/records/[recordId]/analyses/capacity?start=[start of 1 month ago]&end=[last day of current month]' \
--header 'Authorization: apikey XXXX'
````

## Todo
* Try to get a working example

# analyses/powerPeaks
I don't really understand the data that is returned. It seems to return some totals grouped in unlogical groups. I think it returns the 15min intervals that are received from the meter? But with a delay, for instance in the example setup the most recent data I get is 09/10/2023 21:45.

But I don't see a good way to show this in Home Assistant. As there is no way for me to update the data for an entity in the past.

## Todo 
* read https://community.home-assistant.io/t/import-old-energy-readings-for-use-in-energy-dashboard/341406/8
* check how https://github.com/frenck/spook/blob/main/custom_components/spook/ectoplasms/recorder/services/import_statistics.py
works

**Comment by liviooo** [comment]
@tijsverkoyen I will send you email with details

**Comment by maxhelskens** [comment]
## analyses/peakPower

This call returns the 15 minute period with the highest average power per month. If multiple grid-offtake power meters are present for a specific record they are returned as separate series objects.

 ## analyses/capacity
 
 This endpoint is not used and I am honestly surprised to see it still exists and made it into the docs.
 
 ## analyses/powerPeaks
 
This endpoint shows the peaks (above 2.5 kW) in the requested period. A small time series of 2 hours is returned around each peak. This is not a continuous time series an thus not very useful in HA in my opinion.

**Comment by tijsverkoyen** [comment]
@maxhelskens can I assume the peakPower will only happen on meters with:
* `meterType == "electricity"`
* `metric == "gridImportActivePower"`

**Comment by maxhelskens** [comment]
@tijsverkoyen - That is correct.

**Comment by tijsverkoyen** [comment]
> # Change config flow
> When configuring the integration it is asked if a premium subscription is active. If so the analyses entities are created and updated.

Not needed, as I can check on setup if a user has a `premium` or `premiumHr` plan. Although: Home Assistant will need to be restarted to take effect. Should be documented in the release notes.

> # analyses/peakPower
> 
> I would create the following entities, and update them once a day
> 
> * Current Month PeakPower Power (kW)
> * Current Month PeakPower Time (datetime)
> * Last Month PeakPower Power (kw)
> * Last Month PeakPower Time (datetime)
> 
> The data can be retrieved in 1 call. So only 1 coordinator for these entities is needed.
> 
> ````
> curl --location 'https://api.energyid.eu//api/v1/records/[recordId]/analyses/peakPower?start=[start of 1 month ago]&end=[last day of current month]' \
> --header 'Authorization: apikey XXXX'
> ````

Implemented in https://github.com/tijsverkoyen/HomeAssistant-EnergyID/pull/15
I will create a release in a few minutes.

> # analyses/capacity
> I don't have a working example at the moment, but purely based on the documentation I think the following entities would be beneficial:
> 
> * Current Month Capacity Total (Wh)
> * Current Month Capacity Min (Wh)
> * Current Month Capacity Max (Wh)
> * Current Month Capacity Mean (Wh)
> 
> The data can be retrieved in 1 call. So only 1 coordinator for these entities is needed.
> 
> ````
> curl --location 'https://api.energyid.eu//api/v1/records/[recordId]/analyses/capacity?start=[start of 1 month ago]&end=[last day of current month]' \
> --header 'Authorization: apikey XXXX'
> ````

Will not be implemented. As @maxhelskens [told](https://github.com/tijsverkoyen/HomeAssistant-EnergyID/issues/12#issuecomment-1757547706) this endpoint should not be used

> # analyses/powerPeaks
> I don't really understand the data that is returned. It seems to return some totals grouped in unlogical groups. I think it returns the 15min intervals that are received from the meter? But with a delay, for instance in the example setup the most recent data I get is 09/10/2023 21:45.
> 
> But I don't see a good way to show this in Home Assistant. As there is no way for me to update the data for an entity in the past.

As @maxhelskens told this is not really a continuous data serie. And in Home Assistant there is no real good way to push historical data for entities. So I will not implement this.
