### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by ivonulens** [tijsverkoyen/HomeAssistant-EnergyID#16]
Ik krijg enegyid wel toegevoegd maar krijg geen sensors, kan ik hier iets meer uitleg over krijgen

**Comment by tijsverkoyen** [comment]
Could you try to restart Home Assistant.
See https://github.com/tijsverkoyen/HomeAssistant-EnergyID/issues/11

**Comment by ivonulens** [comment]
het werkt Thanks
