### ISSUE TITLE
PeakPower broken?

### ISSUE THREAD

**Issue by liviooo** [tijsverkoyen/HomeAssistant-EnergyID#17]
Since an HA update on Dec. 4th there is an error in the integration.

The "sensor.elektrisch_afnamevermogen_mijn_woning_elektrisch_afnamevermogen_current_month_peakpower_power", 
"sensor.elektrisch_afnamevermogen_mijn_woning_elektrisch_afnamevermogen_last_month_peakpower_datetime", etc ... are not returning any values anymore.

Elektrisch afnamevermogen Mijn woning: Elektrisch afnamevermogen - Last month PeakPower Datetime
unknown

![Screenshot 2023-12-11 at 12 21 50](https://github.com/tijsverkoyen/HomeAssistant-EnergyID/assets/23534/805583ac-a979-4b3f-ae22-858d3e7d0cea)
![Screenshot 2023-12-11 at 12 20 17](https://github.com/tijsverkoyen/HomeAssistant-EnergyID/assets/23534/a3c48660-809b-47dc-b265-782a54f34b76)
![Screenshot 2023-12-11 at 12 19 17](https://github.com/tijsverkoyen/HomeAssistant-EnergyID/assets/23534/e4bbf764-d59b-4554-a433-a34c8c1b2cd2)

**Comment by tijsverkoyen** [comment]
Do you see anything in the logs?

**Comment by tijsverkoyen** [comment]
Can you enable debug logging for the integration and check again?
See https://www.home-assistant.io/integrations/logger/

**Comment by tijsverkoyen** [comment]
Thx. Will look into it. Probably next week.

**Comment by tijsverkoyen** [comment]
It seems that EnergyID removed the endpoints to fetch the peak power data.
I don't see an alternative in their documentation. 

At the moment I don't see a real solution. I have contacted EnergyID. But don't get your hopes up.

**Comment by tijsverkoyen** [comment]
Magic...

**Comment by tijsverkoyen** [comment]
As I understand from the mailconversation with Diedrik it should be resolved.
