### ISSUE TITLE
Warning regarding "async_forward_entry_setup"

### ISSUE THREAD

**Issue by willembuys** [tijsverkoyen/HomeAssistant-EnergyID#19]
I get below warning and since it might impact future HA releases, thought I'd raise it as an issue. Thanks for looking into it, it's such a useful integration to get Fluvius data in HA.

"Detected code that calls async_forward_entry_setup for integration energy_id with title: EnergyID and entry_id: xxx, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue."

**Comment by tijsverkoyen** [comment]
Fixed in https://github.com/tijsverkoyen/HomeAssistant-EnergyID/releases/tag/v1.3.2

**Comment by willembuys** [comment]
Great, warning is gone. Thanks for the quick action!
