### ISSUE TITLE
Warning in HA log

### ISSUE THREAD

**Issue by liviooo** [tijsverkoyen/HomeAssistant-EnergyID#21]
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'energy_id' uses `async_config_entry_first_refresh`, which is only supported when entry state is ConfigEntryState.SETUP_IN_PROGRESS, but it is in state ConfigEntryState.LOADED, This will stop working in Home Assistant 2025.11 at custom_components/energy_id/sensor.py, line 72: await record_peak_power_coordinator.async_config_entry_first_refresh(), please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-EnergyID/issues

**Comment by tijsverkoyen** [comment]
This is fixed in https://github.com/tijsverkoyen/HomeAssistant-EnergyID/releases/tag/v1.3.3
