### ISSUE TITLE
No sensors visible

### ISSUE THREAD

**Issue by patagonista** [tijsverkoyen/HomeAssistant-EnergyID#9]
I've added energyID via a custom repository in HACS and was able to configure my RecordID and API key (read and Write) to the integration. Just as mentioned on you Read me page.

The integration is installed but there are no sensors or services visible. Any idea what went wrong?

**Comment by tijsverkoyen** [comment]
Not really a clue at the moment.

Could you enable debug-mode and try to install the integration again? And check if there is any output in the logs.
